version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1973
      - 55038:52773
      - 53774
    volumes:
      - ./:/irisrun/repo